TALOS_VERSION ?= v1.13.0
ARCH ?= amd64
MONO_CORE_DIR ?= ../mono-core
OUT_DIR ?= _out
RELEASE_CHANNEL ?= testnet
CHAIN_PROFILE ?= testnet
CHAIN_ID ?= 69420
GENESIS_TOML ?= defaults/$(CHAIN_PROFILE)/genesis.toml
KERNEL_BASELINE_FILE ?= kernel-hardening-baseline.json
DM_VERITY_EXPECTED_ROOT_HASHES ?=
DM_VERITY_SUBSTRATE_PROOF ?= $(OUT_DIR)/smoke-qemu/substrate-runtime.json
DM_VERITY_ROOT_HASH_FORMAT ?= lines
PROTOCORE_P2P_LISTEN ?= /ip4/0.0.0.0/tcp/29898
PROTOCORE_RPC_LISTEN ?= 0.0.0.0:8545
PROTOCORE_DISCOVERY ?= hybrid
PROTOCORE_REQUIRE_ENROLLMENT ?= false
PROTOCORE_ENROLLMENT_FILE ?= /var/lib/protocore/enrollment/enrollment.json
PROTOCORE_EXPECTED_DIGEST_FILE ?=
PROTOCORE_REQUIRE_TPM_BINDING ?= false
PROTOCORE_TPM_QUOTE_FILE ?=
PROTOCORE_TPM_EVENT_LOG_FILE ?=
PROTOCORE_TPM_SEALED_BLS_SHARE_FILE ?=
PROTOCORE_DKG_TRANSCRIPT_FILE ?=
PROTOCORE_LYTHIUMSEAL_OPERATOR_KEY_FILE ?=
PROTOCORE_GENERATE_LYTHIUMSEAL_OPERATOR_KEY ?=
PROTOCORE_LYTHIUMSEAL_OPERATOR_INDEX ?=
PROTOCORE_LYTHIUMSEAL_OPERATOR_EPOCH ?=
MONARCH_DESKTOP_MIN_VERSION ?= 0.0.5
MONARCH_DESKTOP_MAX_VERSION ?= <1.0.0
MONARCH_DESKTOP_CHANNEL ?= $(RELEASE_CHANNEL)
UPGRADE_REQUIRES_SAME_CHANNEL ?= true
STATE_MIGRATION_REQUIRED ?= false
STATE_MIGRATION_MODE ?= none
STATE_MIGRATION_RUNBOOK_ID ?=
ROLLBACK_SUPPORTED ?= true
REQUIRE_SIGNATURES ?= false
REQUIRE_SMOKE_QEMU ?= false
REQUIRE_CHANNEL_METADATA ?= false
REQUIRE_COMPLETE_ARTIFACT_SET ?= false
REQUIRE_SUBSTRATE_PROOF ?= false
REQUIRE_NETWORK_POLICY ?= false
REQUIRE_PROVISIONING_POLICY ?= false
REQUIRE_INCIDENT_RESPONSE_POLICY ?= false
REQUIRE_DISASTER_RECOVERY_POLICY ?= false
REQUIRE_AUDIT_TRAIL_POLICY ?= false
REQUIRE_SMOKE_QEMU_CONFIG_APPLY ?= false
REQUIRE_SMOKE_QEMU_SERVICE ?= false
REQUIRE_SMOKE_QEMU_RPC ?= false
REQUIRE_SMOKE_QEMU_TALOSCTL ?= false
REQUIRE_ENROLLMENT_RUNTIME_PROOF ?= false
REQUIRE_TPM_BINDING_RUNTIME_PROOF ?= false
REQUIRE_SUBSTRATE_RUNTIME_PROOF ?= false
REQUIRE_DM_VERITY_ACTIVE ?= false
REQUIRE_COSIGN_SIGNATURES ?= false
REQUIRE_GITHUB_ATTESTATIONS ?= false
ATTESTATION_MODE ?= online
ATTESTATION_BUNDLE_DIR ?=
TRUSTED_ROOT_FILE ?=
REQUIRE_SOURCE_MATCH ?= false
REQUIRE_MONO_CORE_SOURCE_MATCH ?= false
ALLOW_DIRTY_SOURCE ?= false
RUN_REBUILD ?= false
REBUILD_OUT_DIR ?=
REQUIRE_REBUILD_ALL ?= false
RUN_RELEASE_REBUILD_WITNESS ?= false
REQUIRE_RELEASE_REBUILD_WITNESS ?= false
RELEASE_REBUILD_WITNESS_PATH ?=
RUN_EXTENSION_REBUILD ?= false
REQUIRE_EXTENSION_REBUILD_WITNESS ?= false
REBUILD_WITNESS_PATH ?=
PROTOCORE_BINARY ?=
REQUIRE_TALOS_API_PROBE ?= false
TALOS_MACHINE_CONFIG_FILE ?=
TALOSCONFIG_FILE ?=
REQUIRE_EXTENSION_SERVICE_CHECK ?= false
REQUIRE_PROTOCORE_RPC_PROBE ?= false
EXTENSION_SERVICE_REQUIRED_STATE ?=
UPGRADE_CURRENT_METADATA ?=
UPGRADE_TARGET_METADATA ?=
UPGRADE_IMAGE_REF ?=
UPGRADE_STAGE ?= false
UPGRADE_REBOOT_MODE ?= default
UPGRADE_PLAN_OUTPUT ?=
FLEET_MANIFEST ?=
FLEET_PLAN_OUTPUT ?=
ALLOW_SIGNING_QUORUM_RISK ?= false
TALOS_NODES ?=
TALOS_ENDPOINTS ?=
PROMOTION_METADATA ?=
RELEASE_METADATA ?= $(PROMOTION_METADATA)
CHANNEL_POLICY_FILE ?= channel-policy.json
RUN_ARTIFACT_VERIFIER ?= true
RUN_PROVENANCE_VERIFIER ?= true
DESKTOP_E2E_EVIDENCE ?=
DESKTOP_E2E_REPO ?= monolythium/monarch-desktop
DESKTOP_E2E_RELEASE_TAG ?=
DESKTOP_E2E_ARTIFACT_RUN_ID ?=
DESKTOP_E2E_ARTIFACT_NAME ?= monarch-desktop-e2e-evidence
DESKTOP_E2E_EVIDENCE_URL ?=
DESKTOP_E2E_DOWNLOAD_DIR ?= $(OUT_DIR)/desktop-e2e-evidence
ALLOW_GENESIS_CHANGE ?= false
ALLOW_STATE_MIGRATION ?= false
ALLOW_DIRTY_RELEASE ?= false
SMOKE_CONFIG_DIR ?= $(OUT_DIR)/smoke-qemu-config
SMOKE_CLUSTER_NAME ?= monarch-smoke
SMOKE_CLUSTER_ENDPOINT ?= https://127.0.0.1:6443
TALOS_INSTALL_DISK ?= /dev/vda
TALOS_ADDITIONAL_SANS ?= 127.0.0.1
ENROLLMENT_MANIFEST ?=
ENROLLMENT_ON_CHAIN_OUTPUT_DIR ?= $(OUT_DIR)/on-chain-enrollment
ENROLLMENT_ON_CHAIN_MANIFEST ?=
ENROLLMENT_ON_CHAIN_SUMMARY ?=
ENROLLMENT_ON_CHAIN_COMMAND ?=
ENROLLMENT_ON_CHAIN_COMMAND_LABEL ?=
ENROLLMENT_ON_CHAIN_STRICT ?= true
ENROLLMENT_REGISTRY_CONTRACT ?=
KEY_SHARE_CEREMONY ?=
KEY_SHARE_HANDOFF ?=
TPM_SEALING_EVIDENCE ?=
TPM_SEALING_EVIDENCE_FILES ?=
ENROLLMENT_MANIFEST_FILES ?=
KEY_SHARE_CEREMONY_RUN_OUTPUT_DIR ?= $(OUT_DIR)/key-share-ceremony
REQUIRE_TPM_SEALING_EVIDENCE ?= false
REQUIRE_DKG_RESHARE_ATTESTATION ?= false
DKG_RESHARE_ATTESTATION_INPUT ?=
DKG_RESHARE_ATTESTATION_OUTPUT ?=
DKG_RESHARE_INTENT_ID ?=
DKG_RESHARE_BLS_PUBLIC_KEYS_HEX ?=
DKG_RESHARE_THRESHOLD_SIG_HEX ?=
DKG_RESHARE_ATTESTATION ?=
DKG_RESHARE_CREATED_AT ?=
PRODUCTION_DKG_OUTPUT_DIR ?= $(OUT_DIR)/production-dkg-ceremony
PRODUCTION_DKG_SUMMARY ?=
PRODUCTION_DKG_STRICT ?= true
DKG_CEREMONY_COMMAND ?=
DKG_CEREMONY_COMMAND_LABEL ?=
REQUIRE_EXTERNAL_DKG_ATTESTATION_FILE ?= true
OPERATOR_AUDIT_TRAIL ?=
OPERATOR_INDEX ?=
HANDOFF_SEALED_SHARE_FILE ?=
HANDOFF_DKG_TRANSCRIPT_FILE ?=
HANDOFF_CEREMONY_FILE ?=
HANDOFF_ID ?=
HANDOFF_CREATED_AT ?=
TALOS_CERTIFICATE_ROTATION ?=
INCIDENT_RESPONSE ?=
DISASTER_RECOVERY ?=
PROTOCORE_DATA_DIR ?=
BACKUP_RELEASE_METADATA ?=
BACKUP_OUTPUT_DIR ?= $(OUT_DIR)/protocore-backups
BACKUP_NODE_ID ?=
BACKUP_NODE_ROLE ?= archive
BACKUP_MODE ?= stopped-protocore-archive
BACKUP_SERVICE_STATE ?=
BACKUP_SERVICE_EVIDENCE ?=
BACKUP_ARCHIVE_NAME ?=
BACKUP_OVERWRITE ?= false
RESTORE_BACKUP_MANIFEST ?=
RESTORE_OUTPUT_DIR ?=
RESTORE_SERVICE_STATE ?=
RESTORE_SERVICE_EVIDENCE ?=
RESTORE_EVIDENCE_OUTPUT ?=
RESTORE_RELEASE_METADATA ?=
RESTORE_OVERWRITE ?= false
EXPECTED_CHAIN_PROFILE ?=
EXPECTED_CHAIN_ID ?=
REQUIRE_RELEASE_DIGEST ?= false
REQUIRE_ON_CHAIN_REGISTRATION ?= false
ALLOW_PENDING_ON_CHAIN_REGISTRATION ?= false
REQUIRE_TPM_ATTESTATION_EVIDENCE ?= false
LOCAL_EVIDENCE_ROOT ?=
VERIFY_LOCAL_FILES ?= auto
REQUIRE_TPM2_CHECKQUOTE ?= auto
REQUIRE_ON_CHAIN_LIFECYCLE ?= false
REQUIRE_HARDWARE_TPM ?= false
REQUIRE_DESKTOP_EVIDENCE ?= false
MIN_CERT_VALIDITY_DAYS ?= 30
REQUIRE_FOUNDATION_AUTHORIZATION ?= false
REQUIRE_ON_CHAIN_ACTION ?= false
REQUIRE_ON_CHAIN_RECOVERY ?= false
NETWORK_POLICY_METADATA ?=
NETWORK_FIREWALL_FORMAT ?= nftables
NETWORK_FIREWALL_OUTPUT ?=
TALOS_ALLOWED_CIDRS ?=
RPC_ALLOWED_CIDRS ?=
P2P_ALLOWED_CIDRS ?= 0.0.0.0/0,::/0
ALLOW_PUBLIC_TALOS ?= false
ALLOW_PUBLIC_RPC ?= false
HCLOUD_FIREWALL_NAME ?= monarch-node
HCLOUD_FIREWALL_APPLY ?= false
HCLOUD_FIREWALL_RULES_OUTPUT ?=
HCLOUD_FIREWALL_SERVERS ?=
HCLOUD_FIREWALL_SERVER_SELECTOR ?=
HCLOUD_FIREWALL_LABELS ?= app=monarch-os,component=protocore
CLOUD_FIREWALL_PROVIDER ?= all
CLOUD_FIREWALL_NAME ?= monarch-node
CLOUD_FIREWALL_OUTPUT ?=
DIGITALOCEAN_DROPLET_IDS ?=
DIGITALOCEAN_TAGS ?= monarch-os
AWS_SECURITY_GROUP_ID ?=
AWS_SECURITY_GROUP_NAME ?= monarch-node
AWS_VPC_ID ?=
GCP_NETWORK ?= default
GCP_TARGET_TAGS ?= monarch-os
VULTR_FIREWALL_GROUP_ID ?=

.PHONY: build iso metal extension metadata dm-verity-root-hashes extension-rebuild-witness release-rebuild-witness verify-artifacts verify-provenance verify-desktop-e2e resolve-desktop-e2e check-upgrade-readiness upgrade-plan fleet-upgrade-plan test-upgrade-plan test-fleet-upgrade-plan check-channel-promotion validate-enrollment-manifest validate-tpm-attestation-evidence run-on-chain-enrollment validate-tpm-sealing-evidence validate-key-share-ceremony run-key-share-ceremony run-production-dkg-ceremony render-key-share-handoff render-dkg-reshare-attestation validate-key-share-handoff test-on-chain-enrollment-runner test-key-share-ceremony-runner test-production-dkg-ceremony-runner test-key-share-handoff test-dkg-reshare-attestation test-enrollment-and-key-share-validators test-tpm-sealing-evidence validate-operator-audit-trail test-operator-audit-trail validate-talos-certificate-rotation test-talos-certificate-rotation validate-incident-response test-incident-response validate-disaster-recovery test-disaster-recovery protocore-offline-backup protocore-offline-restore test-protocore-offline-backup test-protocore-offline-restore network-firewall-policy hcloud-firewall-policy cloud-firewall-policy test-network-firewall-policy smoke-qemu-config smoke-qemu smoke-qemu-artifact clean sbom

build: iso metal

iso:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" MONO_CORE_DIR="$(MONO_CORE_DIR)" OUT_DIR="$(OUT_DIR)" CHAIN_PROFILE="$(CHAIN_PROFILE)" CHAIN_ID="$(CHAIN_ID)" GENESIS_TOML="$(GENESIS_TOML)" DM_VERITY_EXPECTED_ROOT_HASHES="$(DM_VERITY_EXPECTED_ROOT_HASHES)" PROTOCORE_P2P_LISTEN="$(PROTOCORE_P2P_LISTEN)" PROTOCORE_RPC_LISTEN="$(PROTOCORE_RPC_LISTEN)" PROTOCORE_DISCOVERY="$(PROTOCORE_DISCOVERY)" PROTOCORE_REQUIRE_ENROLLMENT="$(PROTOCORE_REQUIRE_ENROLLMENT)" PROTOCORE_ENROLLMENT_FILE="$(PROTOCORE_ENROLLMENT_FILE)" PROTOCORE_EXPECTED_DIGEST_FILE="$(PROTOCORE_EXPECTED_DIGEST_FILE)" PROTOCORE_REQUIRE_TPM_BINDING="$(PROTOCORE_REQUIRE_TPM_BINDING)" PROTOCORE_TPM_QUOTE_FILE="$(PROTOCORE_TPM_QUOTE_FILE)" PROTOCORE_TPM_EVENT_LOG_FILE="$(PROTOCORE_TPM_EVENT_LOG_FILE)" PROTOCORE_TPM_SEALED_BLS_SHARE_FILE="$(PROTOCORE_TPM_SEALED_BLS_SHARE_FILE)" PROTOCORE_DKG_TRANSCRIPT_FILE="$(PROTOCORE_DKG_TRANSCRIPT_FILE)" ./scripts/build-iso.sh

metal:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" MONO_CORE_DIR="$(MONO_CORE_DIR)" OUT_DIR="$(OUT_DIR)" CHAIN_PROFILE="$(CHAIN_PROFILE)" CHAIN_ID="$(CHAIN_ID)" GENESIS_TOML="$(GENESIS_TOML)" DM_VERITY_EXPECTED_ROOT_HASHES="$(DM_VERITY_EXPECTED_ROOT_HASHES)" PROTOCORE_P2P_LISTEN="$(PROTOCORE_P2P_LISTEN)" PROTOCORE_RPC_LISTEN="$(PROTOCORE_RPC_LISTEN)" PROTOCORE_DISCOVERY="$(PROTOCORE_DISCOVERY)" PROTOCORE_REQUIRE_ENROLLMENT="$(PROTOCORE_REQUIRE_ENROLLMENT)" PROTOCORE_ENROLLMENT_FILE="$(PROTOCORE_ENROLLMENT_FILE)" PROTOCORE_EXPECTED_DIGEST_FILE="$(PROTOCORE_EXPECTED_DIGEST_FILE)" PROTOCORE_REQUIRE_TPM_BINDING="$(PROTOCORE_REQUIRE_TPM_BINDING)" PROTOCORE_TPM_QUOTE_FILE="$(PROTOCORE_TPM_QUOTE_FILE)" PROTOCORE_TPM_EVENT_LOG_FILE="$(PROTOCORE_TPM_EVENT_LOG_FILE)" PROTOCORE_TPM_SEALED_BLS_SHARE_FILE="$(PROTOCORE_TPM_SEALED_BLS_SHARE_FILE)" PROTOCORE_DKG_TRANSCRIPT_FILE="$(PROTOCORE_DKG_TRANSCRIPT_FILE)" ./scripts/build-metal.sh

extension:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" MONO_CORE_DIR="$(MONO_CORE_DIR)" OUT_DIR="$(OUT_DIR)" CHAIN_PROFILE="$(CHAIN_PROFILE)" CHAIN_ID="$(CHAIN_ID)" GENESIS_TOML="$(GENESIS_TOML)" DM_VERITY_EXPECTED_ROOT_HASHES="$(DM_VERITY_EXPECTED_ROOT_HASHES)" PROTOCORE_P2P_LISTEN="$(PROTOCORE_P2P_LISTEN)" PROTOCORE_RPC_LISTEN="$(PROTOCORE_RPC_LISTEN)" PROTOCORE_DISCOVERY="$(PROTOCORE_DISCOVERY)" PROTOCORE_REQUIRE_ENROLLMENT="$(PROTOCORE_REQUIRE_ENROLLMENT)" PROTOCORE_ENROLLMENT_FILE="$(PROTOCORE_ENROLLMENT_FILE)" PROTOCORE_EXPECTED_DIGEST_FILE="$(PROTOCORE_EXPECTED_DIGEST_FILE)" PROTOCORE_REQUIRE_TPM_BINDING="$(PROTOCORE_REQUIRE_TPM_BINDING)" PROTOCORE_TPM_QUOTE_FILE="$(PROTOCORE_TPM_QUOTE_FILE)" PROTOCORE_TPM_EVENT_LOG_FILE="$(PROTOCORE_TPM_EVENT_LOG_FILE)" PROTOCORE_TPM_SEALED_BLS_SHARE_FILE="$(PROTOCORE_TPM_SEALED_BLS_SHARE_FILE)" PROTOCORE_DKG_TRANSCRIPT_FILE="$(PROTOCORE_DKG_TRANSCRIPT_FILE)" ./scripts/build-protocore-extension.sh

metadata:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" MONO_CORE_DIR="$(MONO_CORE_DIR)" OUT_DIR="$(OUT_DIR)" RELEASE_CHANNEL="$(RELEASE_CHANNEL)" CHAIN_PROFILE="$(CHAIN_PROFILE)" CHAIN_ID="$(CHAIN_ID)" GENESIS_TOML="$(GENESIS_TOML)" KERNEL_BASELINE_FILE="$(KERNEL_BASELINE_FILE)" DM_VERITY_EXPECTED_ROOT_HASHES="$(DM_VERITY_EXPECTED_ROOT_HASHES)" PROTOCORE_P2P_LISTEN="$(PROTOCORE_P2P_LISTEN)" PROTOCORE_RPC_LISTEN="$(PROTOCORE_RPC_LISTEN)" PROTOCORE_DISCOVERY="$(PROTOCORE_DISCOVERY)" PROTOCORE_REQUIRE_ENROLLMENT="$(PROTOCORE_REQUIRE_ENROLLMENT)" PROTOCORE_ENROLLMENT_FILE="$(PROTOCORE_ENROLLMENT_FILE)" PROTOCORE_EXPECTED_DIGEST_FILE="$(PROTOCORE_EXPECTED_DIGEST_FILE)" PROTOCORE_REQUIRE_TPM_BINDING="$(PROTOCORE_REQUIRE_TPM_BINDING)" PROTOCORE_TPM_QUOTE_FILE="$(PROTOCORE_TPM_QUOTE_FILE)" PROTOCORE_TPM_EVENT_LOG_FILE="$(PROTOCORE_TPM_EVENT_LOG_FILE)" PROTOCORE_TPM_SEALED_BLS_SHARE_FILE="$(PROTOCORE_TPM_SEALED_BLS_SHARE_FILE)" PROTOCORE_DKG_TRANSCRIPT_FILE="$(PROTOCORE_DKG_TRANSCRIPT_FILE)" MONARCH_DESKTOP_MIN_VERSION="$(MONARCH_DESKTOP_MIN_VERSION)" MONARCH_DESKTOP_MAX_VERSION="$(MONARCH_DESKTOP_MAX_VERSION)" MONARCH_DESKTOP_CHANNEL="$(MONARCH_DESKTOP_CHANNEL)" UPGRADE_REQUIRES_SAME_CHANNEL="$(UPGRADE_REQUIRES_SAME_CHANNEL)" STATE_MIGRATION_REQUIRED="$(STATE_MIGRATION_REQUIRED)" STATE_MIGRATION_MODE="$(STATE_MIGRATION_MODE)" STATE_MIGRATION_RUNBOOK_ID="$(STATE_MIGRATION_RUNBOOK_ID)" ROLLBACK_SUPPORTED="$(ROLLBACK_SUPPORTED)" ./scripts/write-release-metadata.sh

dm-verity-root-hashes:
	env OUT_DIR="$(OUT_DIR)" FORMAT="$(DM_VERITY_ROOT_HASH_FORMAT)" ./scripts/extract-dm-verity-root-hashes.sh "$(DM_VERITY_SUBSTRATE_PROOF)"

extension-rebuild-witness:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" MONO_CORE_DIR="$(MONO_CORE_DIR)" OUT_DIR="$(OUT_DIR)" REBUILD_OUT_DIR="$(REBUILD_OUT_DIR)" REBUILD_WITNESS_PATH="$(REBUILD_WITNESS_PATH)" PROTOCORE_BINARY="$(PROTOCORE_BINARY)" ./scripts/check-extension-rebuild-witness.sh

release-rebuild-witness:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" MONO_CORE_DIR="$(MONO_CORE_DIR)" OUT_DIR="$(OUT_DIR)" REBUILD_OUT_DIR="$(REBUILD_OUT_DIR)" RELEASE_REBUILD_WITNESS_PATH="$(RELEASE_REBUILD_WITNESS_PATH)" PROTOCORE_BINARY="$(PROTOCORE_BINARY)" ./scripts/check-release-rebuild-witness.sh

verify-artifacts:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" OUT_DIR="$(OUT_DIR)" KERNEL_BASELINE_FILE="$(KERNEL_BASELINE_FILE)" REQUIRE_SIGNATURES="$(REQUIRE_SIGNATURES)" REQUIRE_SMOKE_QEMU="$(REQUIRE_SMOKE_QEMU)" REQUIRE_CHANNEL_METADATA="$(REQUIRE_CHANNEL_METADATA)" REQUIRE_COMPLETE_ARTIFACT_SET="$(REQUIRE_COMPLETE_ARTIFACT_SET)" REQUIRE_SUBSTRATE_PROOF="$(REQUIRE_SUBSTRATE_PROOF)" REQUIRE_NETWORK_POLICY="$(REQUIRE_NETWORK_POLICY)" REQUIRE_PROVISIONING_POLICY="$(REQUIRE_PROVISIONING_POLICY)" REQUIRE_INCIDENT_RESPONSE_POLICY="$(REQUIRE_INCIDENT_RESPONSE_POLICY)" REQUIRE_DISASTER_RECOVERY_POLICY="$(REQUIRE_DISASTER_RECOVERY_POLICY)" REQUIRE_AUDIT_TRAIL_POLICY="$(REQUIRE_AUDIT_TRAIL_POLICY)" REQUIRE_SMOKE_QEMU_CONFIG_APPLY="$(REQUIRE_SMOKE_QEMU_CONFIG_APPLY)" REQUIRE_SMOKE_QEMU_SERVICE="$(REQUIRE_SMOKE_QEMU_SERVICE)" REQUIRE_SMOKE_QEMU_RPC="$(REQUIRE_SMOKE_QEMU_RPC)" REQUIRE_SMOKE_QEMU_TALOSCTL="$(REQUIRE_SMOKE_QEMU_TALOSCTL)" REQUIRE_ENROLLMENT_RUNTIME_PROOF="$(REQUIRE_ENROLLMENT_RUNTIME_PROOF)" REQUIRE_TPM_BINDING_RUNTIME_PROOF="$(REQUIRE_TPM_BINDING_RUNTIME_PROOF)" REQUIRE_SUBSTRATE_RUNTIME_PROOF="$(REQUIRE_SUBSTRATE_RUNTIME_PROOF)" REQUIRE_DM_VERITY_ACTIVE="$(REQUIRE_DM_VERITY_ACTIVE)" ./scripts/verify-release-artifacts.sh

verify-provenance:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" OUT_DIR="$(OUT_DIR)" REQUIRE_COSIGN_SIGNATURES="$(REQUIRE_COSIGN_SIGNATURES)" REQUIRE_GITHUB_ATTESTATIONS="$(REQUIRE_GITHUB_ATTESTATIONS)" ATTESTATION_MODE="$(ATTESTATION_MODE)" ATTESTATION_BUNDLE_DIR="$(ATTESTATION_BUNDLE_DIR)" TRUSTED_ROOT_FILE="$(TRUSTED_ROOT_FILE)" REQUIRE_SOURCE_MATCH="$(REQUIRE_SOURCE_MATCH)" REQUIRE_MONO_CORE_SOURCE_MATCH="$(REQUIRE_MONO_CORE_SOURCE_MATCH)" ALLOW_DIRTY_SOURCE="$(ALLOW_DIRTY_SOURCE)" RUN_REBUILD="$(RUN_REBUILD)" REBUILD_OUT_DIR="$(REBUILD_OUT_DIR)" REQUIRE_REBUILD_ALL="$(REQUIRE_REBUILD_ALL)" RUN_RELEASE_REBUILD_WITNESS="$(RUN_RELEASE_REBUILD_WITNESS)" REQUIRE_RELEASE_REBUILD_WITNESS="$(REQUIRE_RELEASE_REBUILD_WITNESS)" RELEASE_REBUILD_WITNESS_PATH="$(RELEASE_REBUILD_WITNESS_PATH)" RUN_EXTENSION_REBUILD="$(RUN_EXTENSION_REBUILD)" REQUIRE_EXTENSION_REBUILD_WITNESS="$(REQUIRE_EXTENSION_REBUILD_WITNESS)" REBUILD_WITNESS_PATH="$(REBUILD_WITNESS_PATH)" PROTOCORE_BINARY="$(PROTOCORE_BINARY)" MONO_CORE_DIR="$(MONO_CORE_DIR)" ./scripts/verify-release-provenance.sh

verify-desktop-e2e:
	env DESKTOP_E2E_EVIDENCE="$(DESKTOP_E2E_EVIDENCE)" RELEASE_METADATA="$(RELEASE_METADATA)" ./scripts/verify-desktop-e2e-evidence.sh "$(DESKTOP_E2E_EVIDENCE)" "$(RELEASE_METADATA)"

resolve-desktop-e2e:
	env OUT_DIR="$(OUT_DIR)" DESKTOP_E2E_EVIDENCE="$(DESKTOP_E2E_EVIDENCE)" DESKTOP_E2E_REPO="$(DESKTOP_E2E_REPO)" DESKTOP_E2E_RELEASE_TAG="$(DESKTOP_E2E_RELEASE_TAG)" DESKTOP_E2E_ARTIFACT_RUN_ID="$(DESKTOP_E2E_ARTIFACT_RUN_ID)" DESKTOP_E2E_ARTIFACT_NAME="$(DESKTOP_E2E_ARTIFACT_NAME)" DESKTOP_E2E_EVIDENCE_URL="$(DESKTOP_E2E_EVIDENCE_URL)" DESKTOP_E2E_DOWNLOAD_DIR="$(DESKTOP_E2E_DOWNLOAD_DIR)" PROMOTION_METADATA="$(PROMOTION_METADATA)" CHANNEL_POLICY_FILE="$(CHANNEL_POLICY_FILE)" ./scripts/resolve-desktop-e2e-evidence.sh

check-upgrade-readiness:
	env ALLOW_GENESIS_CHANGE="$(ALLOW_GENESIS_CHANGE)" ALLOW_STATE_MIGRATION="$(ALLOW_STATE_MIGRATION)" ALLOW_DIRTY_RELEASE="$(ALLOW_DIRTY_RELEASE)" ./scripts/check-upgrade-readiness.sh "$(UPGRADE_CURRENT_METADATA)" "$(UPGRADE_TARGET_METADATA)"

upgrade-plan:
	env ALLOW_GENESIS_CHANGE="$(ALLOW_GENESIS_CHANGE)" ALLOW_STATE_MIGRATION="$(ALLOW_STATE_MIGRATION)" ALLOW_DIRTY_RELEASE="$(ALLOW_DIRTY_RELEASE)" UPGRADE_IMAGE_REF="$(UPGRADE_IMAGE_REF)" UPGRADE_STAGE="$(UPGRADE_STAGE)" UPGRADE_REBOOT_MODE="$(UPGRADE_REBOOT_MODE)" UPGRADE_PLAN_OUTPUT="$(UPGRADE_PLAN_OUTPUT)" TALOS_NODES="$(TALOS_NODES)" TALOS_ENDPOINTS="$(TALOS_ENDPOINTS)" TALOSCONFIG_FILE="$(TALOSCONFIG_FILE)" DISASTER_RECOVERY="$(DISASTER_RECOVERY)" REQUIRE_ON_CHAIN_RECOVERY="$(REQUIRE_ON_CHAIN_RECOVERY)" ./scripts/render-upgrade-plan.sh "$(UPGRADE_CURRENT_METADATA)" "$(UPGRADE_TARGET_METADATA)"

fleet-upgrade-plan:
	env ALLOW_GENESIS_CHANGE="$(ALLOW_GENESIS_CHANGE)" ALLOW_STATE_MIGRATION="$(ALLOW_STATE_MIGRATION)" ALLOW_DIRTY_RELEASE="$(ALLOW_DIRTY_RELEASE)" ALLOW_SIGNING_QUORUM_RISK="$(ALLOW_SIGNING_QUORUM_RISK)" UPGRADE_IMAGE_REF="$(UPGRADE_IMAGE_REF)" UPGRADE_STAGE="$(UPGRADE_STAGE)" UPGRADE_REBOOT_MODE="$(UPGRADE_REBOOT_MODE)" FLEET_PLAN_OUTPUT="$(FLEET_PLAN_OUTPUT)" TALOSCONFIG_FILE="$(TALOSCONFIG_FILE)" DISASTER_RECOVERY="$(DISASTER_RECOVERY)" REQUIRE_ON_CHAIN_RECOVERY="$(REQUIRE_ON_CHAIN_RECOVERY)" ./scripts/render-fleet-upgrade-plan.sh "$(UPGRADE_CURRENT_METADATA)" "$(UPGRADE_TARGET_METADATA)" "$(FLEET_MANIFEST)"

test-upgrade-plan:
	./scripts/test-upgrade-plan.sh

test-fleet-upgrade-plan:
	./scripts/test-fleet-upgrade-plan.sh

check-channel-promotion:
	env CHANNEL_POLICY_FILE="$(CHANNEL_POLICY_FILE)" RUN_ARTIFACT_VERIFIER="$(RUN_ARTIFACT_VERIFIER)" RUN_PROVENANCE_VERIFIER="$(RUN_PROVENANCE_VERIFIER)" DESKTOP_E2E_EVIDENCE="$(DESKTOP_E2E_EVIDENCE)" ./scripts/check-channel-promotion.sh "$(PROMOTION_METADATA)"

validate-enrollment-manifest:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_RELEASE_DIGEST="$(REQUIRE_RELEASE_DIGEST)" REQUIRE_ON_CHAIN_REGISTRATION="$(REQUIRE_ON_CHAIN_REGISTRATION)" ALLOW_PENDING_ON_CHAIN_REGISTRATION="$(ALLOW_PENDING_ON_CHAIN_REGISTRATION)" REQUIRE_HARDWARE_TPM="$(REQUIRE_HARDWARE_TPM)" ./scripts/validate-enrollment-manifest.sh "$(ENROLLMENT_MANIFEST)"

validate-tpm-attestation-evidence:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_RELEASE_DIGEST="$(REQUIRE_RELEASE_DIGEST)" REQUIRE_ON_CHAIN_REGISTRATION="$(REQUIRE_ON_CHAIN_REGISTRATION)" ALLOW_PENDING_ON_CHAIN_REGISTRATION="$(ALLOW_PENDING_ON_CHAIN_REGISTRATION)" REQUIRE_HARDWARE_TPM="$(REQUIRE_HARDWARE_TPM)" LOCAL_EVIDENCE_ROOT="$(LOCAL_EVIDENCE_ROOT)" REQUIRE_TPM2_CHECKQUOTE="$(REQUIRE_TPM2_CHECKQUOTE)" ./scripts/validate-tpm-attestation-evidence.sh "$(ENROLLMENT_MANIFEST)"

run-on-chain-enrollment:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_RELEASE_DIGEST="$(REQUIRE_RELEASE_DIGEST)" REQUIRE_HARDWARE_TPM="$(REQUIRE_HARDWARE_TPM)" REQUIRE_TPM_ATTESTATION_EVIDENCE="$(REQUIRE_TPM_ATTESTATION_EVIDENCE)" REQUIRE_TPM2_CHECKQUOTE="$(REQUIRE_TPM2_CHECKQUOTE)" LOCAL_EVIDENCE_ROOT="$(LOCAL_EVIDENCE_ROOT)" ENROLLMENT_MANIFEST="$(ENROLLMENT_MANIFEST)" ENROLLMENT_ON_CHAIN_OUTPUT_DIR="$(ENROLLMENT_ON_CHAIN_OUTPUT_DIR)" ENROLLMENT_ON_CHAIN_MANIFEST="$(ENROLLMENT_ON_CHAIN_MANIFEST)" ENROLLMENT_ON_CHAIN_SUMMARY="$(ENROLLMENT_ON_CHAIN_SUMMARY)" ENROLLMENT_ON_CHAIN_COMMAND="$(ENROLLMENT_ON_CHAIN_COMMAND)" ENROLLMENT_ON_CHAIN_COMMAND_LABEL="$(ENROLLMENT_ON_CHAIN_COMMAND_LABEL)" ENROLLMENT_ON_CHAIN_STRICT="$(ENROLLMENT_ON_CHAIN_STRICT)" ENROLLMENT_REGISTRY_CONTRACT="$(ENROLLMENT_REGISTRY_CONTRACT)" ./scripts/run-on-chain-enrollment.sh "$(ENROLLMENT_ON_CHAIN_OUTPUT_DIR)"

validate-tpm-sealing-evidence:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_HARDWARE_TPM="$(REQUIRE_HARDWARE_TPM)" REQUIRE_TPM2_CHECKQUOTE="$(REQUIRE_TPM2_CHECKQUOTE)" LOCAL_EVIDENCE_ROOT="$(LOCAL_EVIDENCE_ROOT)" VERIFY_LOCAL_FILES="$(VERIFY_LOCAL_FILES)" KEY_SHARE_CEREMONY="$(KEY_SHARE_CEREMONY)" ENROLLMENT_MANIFEST="$(ENROLLMENT_MANIFEST)" ./scripts/validate-tpm-sealing-evidence.sh "$(TPM_SEALING_EVIDENCE)"

validate-key-share-ceremony:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_ON_CHAIN_LIFECYCLE="$(REQUIRE_ON_CHAIN_LIFECYCLE)" REQUIRE_HARDWARE_TPM="$(REQUIRE_HARDWARE_TPM)" LOCAL_EVIDENCE_ROOT="$(LOCAL_EVIDENCE_ROOT)" VERIFY_LOCAL_FILES="$(VERIFY_LOCAL_FILES)" ./scripts/validate-key-share-ceremony.sh "$(KEY_SHARE_CEREMONY)"

run-key-share-ceremony:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_ON_CHAIN_LIFECYCLE="$(REQUIRE_ON_CHAIN_LIFECYCLE)" REQUIRE_HARDWARE_TPM="$(REQUIRE_HARDWARE_TPM)" REQUIRE_TPM_SEALING_EVIDENCE="$(REQUIRE_TPM_SEALING_EVIDENCE)" REQUIRE_DKG_RESHARE_ATTESTATION="$(REQUIRE_DKG_RESHARE_ATTESTATION)" REQUIRE_TPM2_CHECKQUOTE="$(REQUIRE_TPM2_CHECKQUOTE)" LOCAL_EVIDENCE_ROOT="$(LOCAL_EVIDENCE_ROOT)" VERIFY_LOCAL_FILES="$(VERIFY_LOCAL_FILES)" TPM_SEALING_EVIDENCE_FILES="$(TPM_SEALING_EVIDENCE_FILES)" ENROLLMENT_MANIFEST_FILES="$(ENROLLMENT_MANIFEST_FILES)" DKG_RESHARE_ATTESTATION_INPUT="$(DKG_RESHARE_ATTESTATION_INPUT)" DKG_RESHARE_ATTESTATION_OUTPUT="$(DKG_RESHARE_ATTESTATION_OUTPUT)" DKG_RESHARE_INTENT_ID="$(DKG_RESHARE_INTENT_ID)" DKG_RESHARE_BLS_PUBLIC_KEYS_HEX="$(DKG_RESHARE_BLS_PUBLIC_KEYS_HEX)" DKG_RESHARE_THRESHOLD_SIG_HEX="$(DKG_RESHARE_THRESHOLD_SIG_HEX)" DKG_RESHARE_CREATED_AT="$(DKG_RESHARE_CREATED_AT)" ./scripts/run-key-share-ceremony.sh "$(KEY_SHARE_CEREMONY)" "$(KEY_SHARE_CEREMONY_RUN_OUTPUT_DIR)"

run-production-dkg-ceremony:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" PRODUCTION_DKG_STRICT="$(PRODUCTION_DKG_STRICT)" REQUIRE_ON_CHAIN_LIFECYCLE="$(REQUIRE_ON_CHAIN_LIFECYCLE)" REQUIRE_HARDWARE_TPM="$(REQUIRE_HARDWARE_TPM)" REQUIRE_TPM_SEALING_EVIDENCE="$(REQUIRE_TPM_SEALING_EVIDENCE)" REQUIRE_DKG_RESHARE_ATTESTATION="$(REQUIRE_DKG_RESHARE_ATTESTATION)" REQUIRE_TPM2_CHECKQUOTE="$(REQUIRE_TPM2_CHECKQUOTE)" REQUIRE_EXTERNAL_DKG_ATTESTATION_FILE="$(REQUIRE_EXTERNAL_DKG_ATTESTATION_FILE)" LOCAL_EVIDENCE_ROOT="$(LOCAL_EVIDENCE_ROOT)" VERIFY_LOCAL_FILES="$(VERIFY_LOCAL_FILES)" TPM_SEALING_EVIDENCE_FILES="$(TPM_SEALING_EVIDENCE_FILES)" ENROLLMENT_MANIFEST_FILES="$(ENROLLMENT_MANIFEST_FILES)" DKG_RESHARE_ATTESTATION_INPUT="$(DKG_RESHARE_ATTESTATION_INPUT)" DKG_RESHARE_ATTESTATION_OUTPUT="$(DKG_RESHARE_ATTESTATION_OUTPUT)" DKG_CEREMONY_COMMAND="$(DKG_CEREMONY_COMMAND)" DKG_CEREMONY_COMMAND_LABEL="$(DKG_CEREMONY_COMMAND_LABEL)" PRODUCTION_DKG_OUTPUT_DIR="$(PRODUCTION_DKG_OUTPUT_DIR)" PRODUCTION_DKG_SUMMARY="$(PRODUCTION_DKG_SUMMARY)" KEY_SHARE_CEREMONY="$(KEY_SHARE_CEREMONY)" KEY_SHARE_CEREMONY_RUN_OUTPUT_DIR="$(KEY_SHARE_CEREMONY_RUN_OUTPUT_DIR)" ./scripts/run-production-dkg-ceremony.sh "$(PRODUCTION_DKG_OUTPUT_DIR)"

render-key-share-handoff:
	env HANDOFF_SEALED_SHARE_FILE="$(HANDOFF_SEALED_SHARE_FILE)" HANDOFF_DKG_TRANSCRIPT_FILE="$(HANDOFF_DKG_TRANSCRIPT_FILE)" HANDOFF_CEREMONY_FILE="$(HANDOFF_CEREMONY_FILE)" HANDOFF_ID="$(HANDOFF_ID)" HANDOFF_CREATED_AT="$(HANDOFF_CREATED_AT)" ./scripts/render-key-share-handoff.sh "$(KEY_SHARE_CEREMONY)" "$(OPERATOR_INDEX)" "$(KEY_SHARE_HANDOFF)"

render-dkg-reshare-attestation:
	env DKG_RESHARE_CREATED_AT="$(DKG_RESHARE_CREATED_AT)" ./scripts/render-dkg-reshare-attestation.sh "$(DKG_RESHARE_INTENT_ID)" "$(DKG_RESHARE_BLS_PUBLIC_KEYS_HEX)" "$(DKG_RESHARE_THRESHOLD_SIG_HEX)" "$(DKG_RESHARE_ATTESTATION)"

validate-key-share-handoff:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_ON_CHAIN_LIFECYCLE="$(REQUIRE_ON_CHAIN_LIFECYCLE)" REQUIRE_HARDWARE_TPM="$(REQUIRE_HARDWARE_TPM)" LOCAL_EVIDENCE_ROOT="$(LOCAL_EVIDENCE_ROOT)" VERIFY_LOCAL_FILES="$(VERIFY_LOCAL_FILES)" ./scripts/validate-key-share-handoff.sh "$(KEY_SHARE_HANDOFF)" "$(KEY_SHARE_CEREMONY)"

test-key-share-ceremony-runner:
	./scripts/test-key-share-ceremony-runner.sh

test-production-dkg-ceremony-runner:
	./scripts/test-production-dkg-ceremony-runner.sh

test-on-chain-enrollment-runner:
	./scripts/test-on-chain-enrollment-runner.sh

test-key-share-handoff:
	./scripts/test-key-share-handoff.sh

test-dkg-reshare-attestation:
	./scripts/test-dkg-reshare-attestation.sh

test-enrollment-and-key-share-validators:
	./scripts/test-enrollment-and-key-share-validators.sh

test-tpm-sealing-evidence:
	./scripts/test-tpm-sealing-evidence.sh

validate-operator-audit-trail:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" LOCAL_EVIDENCE_ROOT="$(LOCAL_EVIDENCE_ROOT)" VERIFY_LOCAL_FILES="$(VERIFY_LOCAL_FILES)" ./scripts/validate-operator-audit-trail.sh "$(OPERATOR_AUDIT_TRAIL)"

test-operator-audit-trail:
	./scripts/test-operator-audit-trail.sh

validate-talos-certificate-rotation:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_DESKTOP_EVIDENCE="$(REQUIRE_DESKTOP_EVIDENCE)" MIN_CERT_VALIDITY_DAYS="$(MIN_CERT_VALIDITY_DAYS)" ./scripts/validate-talos-certificate-rotation.sh "$(TALOS_CERTIFICATE_ROTATION)"

test-talos-certificate-rotation:
	./scripts/test-talos-certificate-rotation.sh

validate-incident-response:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_FOUNDATION_AUTHORIZATION="$(REQUIRE_FOUNDATION_AUTHORIZATION)" REQUIRE_ON_CHAIN_ACTION="$(REQUIRE_ON_CHAIN_ACTION)" ./scripts/validate-incident-response.sh "$(INCIDENT_RESPONSE)"

test-incident-response:
	./scripts/test-incident-response.sh

validate-disaster-recovery:
	env EXPECTED_CHAIN_PROFILE="$(EXPECTED_CHAIN_PROFILE)" EXPECTED_CHAIN_ID="$(EXPECTED_CHAIN_ID)" REQUIRE_ON_CHAIN_RECOVERY="$(REQUIRE_ON_CHAIN_RECOVERY)" ./scripts/validate-disaster-recovery.sh "$(DISASTER_RECOVERY)"

test-disaster-recovery:
	./scripts/test-disaster-recovery.sh

protocore-offline-backup:
	env PROTOCORE_DATA_DIR="$(PROTOCORE_DATA_DIR)" BACKUP_RELEASE_METADATA="$(BACKUP_RELEASE_METADATA)" BACKUP_OUTPUT_DIR="$(BACKUP_OUTPUT_DIR)" BACKUP_NODE_ID="$(BACKUP_NODE_ID)" BACKUP_NODE_ROLE="$(BACKUP_NODE_ROLE)" BACKUP_MODE="$(BACKUP_MODE)" BACKUP_SERVICE_STATE="$(BACKUP_SERVICE_STATE)" BACKUP_SERVICE_EVIDENCE="$(BACKUP_SERVICE_EVIDENCE)" BACKUP_ARCHIVE_NAME="$(BACKUP_ARCHIVE_NAME)" BACKUP_OVERWRITE="$(BACKUP_OVERWRITE)" ./scripts/create-protocore-offline-backup.sh "$(PROTOCORE_DATA_DIR)" "$(BACKUP_RELEASE_METADATA)"

protocore-offline-restore:
	env RESTORE_BACKUP_MANIFEST="$(RESTORE_BACKUP_MANIFEST)" RESTORE_OUTPUT_DIR="$(RESTORE_OUTPUT_DIR)" RESTORE_SERVICE_STATE="$(RESTORE_SERVICE_STATE)" RESTORE_SERVICE_EVIDENCE="$(RESTORE_SERVICE_EVIDENCE)" RESTORE_EVIDENCE_OUTPUT="$(RESTORE_EVIDENCE_OUTPUT)" RESTORE_RELEASE_METADATA="$(RESTORE_RELEASE_METADATA)" RESTORE_OVERWRITE="$(RESTORE_OVERWRITE)" ./scripts/restore-protocore-offline-backup.sh "$(RESTORE_BACKUP_MANIFEST)" "$(RESTORE_OUTPUT_DIR)"

test-protocore-offline-backup:
	./scripts/test-protocore-offline-backup.sh

test-protocore-offline-restore:
	./scripts/test-protocore-offline-restore.sh

network-firewall-policy:
	env NETWORK_POLICY_METADATA="$(NETWORK_POLICY_METADATA)" NETWORK_FIREWALL_FORMAT="$(NETWORK_FIREWALL_FORMAT)" NETWORK_FIREWALL_OUTPUT="$(NETWORK_FIREWALL_OUTPUT)" TALOS_ALLOWED_CIDRS="$(TALOS_ALLOWED_CIDRS)" RPC_ALLOWED_CIDRS="$(RPC_ALLOWED_CIDRS)" P2P_ALLOWED_CIDRS="$(P2P_ALLOWED_CIDRS)" ALLOW_PUBLIC_TALOS="$(ALLOW_PUBLIC_TALOS)" ALLOW_PUBLIC_RPC="$(ALLOW_PUBLIC_RPC)" ./scripts/render-network-firewall.sh

hcloud-firewall-policy:
	env NETWORK_POLICY_METADATA="$(NETWORK_POLICY_METADATA)" TALOS_ALLOWED_CIDRS="$(TALOS_ALLOWED_CIDRS)" RPC_ALLOWED_CIDRS="$(RPC_ALLOWED_CIDRS)" P2P_ALLOWED_CIDRS="$(P2P_ALLOWED_CIDRS)" ALLOW_PUBLIC_TALOS="$(ALLOW_PUBLIC_TALOS)" ALLOW_PUBLIC_RPC="$(ALLOW_PUBLIC_RPC)" HCLOUD_FIREWALL_NAME="$(HCLOUD_FIREWALL_NAME)" HCLOUD_FIREWALL_APPLY="$(HCLOUD_FIREWALL_APPLY)" HCLOUD_FIREWALL_RULES_OUTPUT="$(HCLOUD_FIREWALL_RULES_OUTPUT)" HCLOUD_FIREWALL_SERVERS="$(HCLOUD_FIREWALL_SERVERS)" HCLOUD_FIREWALL_SERVER_SELECTOR="$(HCLOUD_FIREWALL_SERVER_SELECTOR)" HCLOUD_FIREWALL_LABELS="$(HCLOUD_FIREWALL_LABELS)" ./scripts/apply-hcloud-firewall.sh

cloud-firewall-policy:
	env NETWORK_POLICY_METADATA="$(NETWORK_POLICY_METADATA)" TALOS_ALLOWED_CIDRS="$(TALOS_ALLOWED_CIDRS)" RPC_ALLOWED_CIDRS="$(RPC_ALLOWED_CIDRS)" P2P_ALLOWED_CIDRS="$(P2P_ALLOWED_CIDRS)" ALLOW_PUBLIC_TALOS="$(ALLOW_PUBLIC_TALOS)" ALLOW_PUBLIC_RPC="$(ALLOW_PUBLIC_RPC)" CLOUD_FIREWALL_PROVIDER="$(CLOUD_FIREWALL_PROVIDER)" CLOUD_FIREWALL_NAME="$(CLOUD_FIREWALL_NAME)" CLOUD_FIREWALL_OUTPUT="$(CLOUD_FIREWALL_OUTPUT)" DIGITALOCEAN_DROPLET_IDS="$(DIGITALOCEAN_DROPLET_IDS)" DIGITALOCEAN_TAGS="$(DIGITALOCEAN_TAGS)" AWS_SECURITY_GROUP_ID="$(AWS_SECURITY_GROUP_ID)" AWS_SECURITY_GROUP_NAME="$(AWS_SECURITY_GROUP_NAME)" AWS_VPC_ID="$(AWS_VPC_ID)" GCP_NETWORK="$(GCP_NETWORK)" GCP_TARGET_TAGS="$(GCP_TARGET_TAGS)" VULTR_FIREWALL_GROUP_ID="$(VULTR_FIREWALL_GROUP_ID)" ./scripts/render-cloud-firewall-plan.sh

test-network-firewall-policy:
	./scripts/test-network-firewall-policy.sh

smoke-qemu-config:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" OUT_DIR="$(OUT_DIR)" SMOKE_CONFIG_DIR="$(SMOKE_CONFIG_DIR)" SMOKE_CLUSTER_NAME="$(SMOKE_CLUSTER_NAME)" SMOKE_CLUSTER_ENDPOINT="$(SMOKE_CLUSTER_ENDPOINT)" TALOS_INSTALL_DISK="$(TALOS_INSTALL_DISK)" TALOS_ADDITIONAL_SANS="$(TALOS_ADDITIONAL_SANS)" CHAIN_PROFILE="$(CHAIN_PROFILE)" CHAIN_ID="$(CHAIN_ID)" PROTOCORE_P2P_LISTEN="$(PROTOCORE_P2P_LISTEN)" PROTOCORE_RPC_LISTEN="$(PROTOCORE_RPC_LISTEN)" PROTOCORE_DISCOVERY="$(PROTOCORE_DISCOVERY)" PROTOCORE_REQUIRE_ENROLLMENT="$(PROTOCORE_REQUIRE_ENROLLMENT)" PROTOCORE_ENROLLMENT_FILE="$(PROTOCORE_ENROLLMENT_FILE)" PROTOCORE_EXPECTED_DIGEST_FILE="$(PROTOCORE_EXPECTED_DIGEST_FILE)" PROTOCORE_REQUIRE_TPM_BINDING="$(PROTOCORE_REQUIRE_TPM_BINDING)" PROTOCORE_TPM_QUOTE_FILE="$(PROTOCORE_TPM_QUOTE_FILE)" PROTOCORE_TPM_EVENT_LOG_FILE="$(PROTOCORE_TPM_EVENT_LOG_FILE)" PROTOCORE_TPM_SEALED_BLS_SHARE_FILE="$(PROTOCORE_TPM_SEALED_BLS_SHARE_FILE)" PROTOCORE_DKG_TRANSCRIPT_FILE="$(PROTOCORE_DKG_TRANSCRIPT_FILE)" ./scripts/gen-qemu-smoke-config.sh

smoke-qemu: metal
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" OUT_DIR="$(OUT_DIR)" KERNEL_BASELINE_FILE="$(KERNEL_BASELINE_FILE)" CHAIN_PROFILE="$(CHAIN_PROFILE)" CHAIN_ID="$(CHAIN_ID)" PROTOCORE_ENROLLMENT_FILE="$(PROTOCORE_ENROLLMENT_FILE)" PROTOCORE_EXPECTED_DIGEST_FILE="$(PROTOCORE_EXPECTED_DIGEST_FILE)" PROTOCORE_TPM_QUOTE_FILE="$(PROTOCORE_TPM_QUOTE_FILE)" PROTOCORE_TPM_EVENT_LOG_FILE="$(PROTOCORE_TPM_EVENT_LOG_FILE)" PROTOCORE_TPM_SEALED_BLS_SHARE_FILE="$(PROTOCORE_TPM_SEALED_BLS_SHARE_FILE)" PROTOCORE_DKG_TRANSCRIPT_FILE="$(PROTOCORE_DKG_TRANSCRIPT_FILE)" REQUIRE_TALOS_API_PROBE="$(REQUIRE_TALOS_API_PROBE)" TALOS_MACHINE_CONFIG_FILE="$(TALOS_MACHINE_CONFIG_FILE)" TALOSCONFIG_FILE="$(TALOSCONFIG_FILE)" REQUIRE_EXTENSION_SERVICE_CHECK="$(REQUIRE_EXTENSION_SERVICE_CHECK)" REQUIRE_PROTOCORE_RPC_PROBE="$(REQUIRE_PROTOCORE_RPC_PROBE)" REQUIRE_ENROLLMENT_RUNTIME_PROOF="$(REQUIRE_ENROLLMENT_RUNTIME_PROOF)" REQUIRE_TPM_BINDING_RUNTIME_PROOF="$(REQUIRE_TPM_BINDING_RUNTIME_PROOF)" REQUIRE_SUBSTRATE_RUNTIME_PROOF="$(REQUIRE_SUBSTRATE_RUNTIME_PROOF)" EXTENSION_SERVICE_REQUIRED_STATE="$(EXTENSION_SERVICE_REQUIRED_STATE)" ./scripts/smoke-qemu.sh

smoke-qemu-artifact:
	env TALOS_VERSION="$(TALOS_VERSION)" ARCH="$(ARCH)" OUT_DIR="$(OUT_DIR)" KERNEL_BASELINE_FILE="$(KERNEL_BASELINE_FILE)" CHAIN_PROFILE="$(CHAIN_PROFILE)" CHAIN_ID="$(CHAIN_ID)" PROTOCORE_ENROLLMENT_FILE="$(PROTOCORE_ENROLLMENT_FILE)" PROTOCORE_EXPECTED_DIGEST_FILE="$(PROTOCORE_EXPECTED_DIGEST_FILE)" PROTOCORE_TPM_QUOTE_FILE="$(PROTOCORE_TPM_QUOTE_FILE)" PROTOCORE_TPM_EVENT_LOG_FILE="$(PROTOCORE_TPM_EVENT_LOG_FILE)" PROTOCORE_TPM_SEALED_BLS_SHARE_FILE="$(PROTOCORE_TPM_SEALED_BLS_SHARE_FILE)" PROTOCORE_DKG_TRANSCRIPT_FILE="$(PROTOCORE_DKG_TRANSCRIPT_FILE)" REQUIRE_TALOS_API_PROBE="$(REQUIRE_TALOS_API_PROBE)" TALOS_MACHINE_CONFIG_FILE="$(TALOS_MACHINE_CONFIG_FILE)" TALOSCONFIG_FILE="$(TALOSCONFIG_FILE)" REQUIRE_EXTENSION_SERVICE_CHECK="$(REQUIRE_EXTENSION_SERVICE_CHECK)" REQUIRE_PROTOCORE_RPC_PROBE="$(REQUIRE_PROTOCORE_RPC_PROBE)" REQUIRE_ENROLLMENT_RUNTIME_PROOF="$(REQUIRE_ENROLLMENT_RUNTIME_PROOF)" REQUIRE_TPM_BINDING_RUNTIME_PROOF="$(REQUIRE_TPM_BINDING_RUNTIME_PROOF)" REQUIRE_SUBSTRATE_RUNTIME_PROOF="$(REQUIRE_SUBSTRATE_RUNTIME_PROOF)" EXTENSION_SERVICE_REQUIRED_STATE="$(EXTENSION_SERVICE_REQUIRED_STATE)" ./scripts/smoke-qemu.sh

sbom:
	@if [ -f "$(OUT_DIR)/monarch-os-talos-$(TALOS_VERSION)-$(ARCH).iso" ]; then \
		syft packages file:$(OUT_DIR)/monarch-os-talos-$(TALOS_VERSION)-$(ARCH).iso -o spdx-json=$(OUT_DIR)/monarch-os-talos-$(TALOS_VERSION)-$(ARCH).iso.spdx.json; \
	fi
	@if [ -f "$(OUT_DIR)/monarch-os-talos-$(TALOS_VERSION)-$(ARCH).raw" ]; then \
		syft packages file:$(OUT_DIR)/monarch-os-talos-$(TALOS_VERSION)-$(ARCH).raw -o spdx-json=$(OUT_DIR)/monarch-os-talos-$(TALOS_VERSION)-$(ARCH).raw.spdx.json; \
	fi
	@for f in "$(OUT_DIR)"/monarch-*.spdx.json; do \
		if [ -f "$$f" ]; then \
			(cd "$$(dirname "$$f")" && sha256sum "$$(basename "$$f")" > "$$(basename "$$f").sha256"); \
		fi; \
	done

clean:
	rm -rf _build _out
